apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: {CLUSTER_NAME}
  version: {KUBERNETES_VERSION}
  region: {AWS_REGION}

vpc:
  subnets:
    public:
      us-west-2b: { id: subnet-071e5d4501d842fdf }
      us-west-2c: { id: subnet-0606639520eb649ba }
      us-west-2d: { id: subnet-0292f634b0bf87229 }
    private:
      us-west-2b: { id: subnet-0e3fda513a84e4bdd }
      us-west-2c: { id: subnet-0c936b26642804d94 }
      us-west-2d: { id: subnet-04b7de08c070a880e }

kubernetesNetworkConfig:
  ipFamily: IPv4

managedNodeGroups:
  - name: default-node-group
    labels:
      role: default-worker
    instanceType: c6i.xlarge
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    volumeSize: 80
    privateNetworking: true
    volumeType: gp3
    volumeIOPS: 3000
    volumeThroughput: 125
    updateConfig: 
      maxUnavailable: 1